In [1]:
import pandas as pd
import requests

In [19]:
import requests

api_key = "your api key from tbdb"  ###insert api key here
keyword_id = 1721  # Example keyword ID

url = f"https://api.themoviedb.org/3/keyword/{keyword_id}/movies"

params = {
    "api_key": api_key,
    "page": 1
}

response = requests.get(url, params=params)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(f"Error: {response.status_code}")
    print(response.text)

{'id': 1721, 'page': 1, 'results': [{'adult': False, 'backdrop_path': '/pjlxrd646cBYznHoPBWTzz6FujX.jpg', 'genre_ids': [28, 878, 18], 'id': 39254, 'title': 'Real Steel', 'original_language': 'en', 'original_title': 'Real Steel', 'overview': 'Charlie Kenton is a washed-up fighter who retired from the ring when robots took over the sport. After his robot is trashed, he reluctantly teams up with his estranged son to rebuild and train an unlikely contender.', 'popularity': 78.628, 'poster_path': '/4GIeI5K5YdDUkR3mNQBoScpSFEf.jpg', 'release_date': '2011-09-28', 'softcore': False, 'video': False, 'vote_average': 7.097, 'vote_count': 9171}, {'adult': False, 'backdrop_path': '/zxi6WQPVc0uQAG5TtLsKvxYHApC.jpg', 'genre_ids': [16, 28, 14, 12], 'id': 980477, 'title': 'Ne Zha 2', 'original_language': 'zh', 'original_title': '哪吒之魔童闹海', 'overview': 'After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.', 'popularity': 44.5479, 'poster_path': '/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg', 'release_date': '2025-01-29', 'softcore': False, 'video': False, 'vote_average': 8.167, 'vote_count': 700}, {'adult': False, 'backdrop_path': '/xRyINp9KfMLVjRiO5nCsoRDdvvF.jpg', 'genre_ids': [18, 53], 'id': 550, 'title': 'Fight Club', 'original_language': 'en', 'original_title': 'Fight Club', 'overview': 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.', 'popularity': 27.9251, 'poster_path': '/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg', 'release_date': '1999-10-15', 'softcore': False, 'video': False, 'vote_average': 8.4, 'vote_count': 32086}, {'adult': False, 'backdrop_path': '/d354XqicJ7vi48YnPDr1vRk5uhZ.jpg', 'genre_ids': [28, 80, 18, 53], 'id': 49026, 'title': 'The Dark Knight Rises', 'original_language': 'en', 'original_title': 'The Dark Knight Rises', 'overview': "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.", 'popularity': 17.8328, 'poster_path': '/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg', 'release_date': '2012-07-17', 'softcore': False, 'video': False, 'vote_average': 7.796, 'vote_count': 24377}, {'adult': False, 'backdrop_path': '/zdXnJqBaGFVtLoPNuMeKfEYUViZ.jpg', 'genre_ids': [10749, 18], 'id': 11036, 'title': 'The Notebook', 'original_language': 'en', 'original_title': 'The Notebook', 'overview': "An epic love story centered around an older man who reads aloud to a woman with Alzheimer's. From a faded notebook, the old man's words bring to life the story about a couple who is separated by World War II, and is then passionately reunited, seven years later, after they have taken different paths.", 'popularity': 16.3556, 'poster_path': '/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg', 'release_date': '2004-06-25', 'softcore': False, 'video': False, 'vote_average': 7.888, 'vote_count': 12550}, {'adult': False, 'backdrop_path': '/8FWLJHuWB72UXBmiMtxwTvQVumN.jpg', 'genre_ids': [10751, 35, 80, 12, 16], 'id': 1175942, 'title': 'The Bad Guys 2', 'original_language': 'en', 'original_title': 'The Bad Guys 2', 'overview': 'The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.', 'popularity': 14.9456, 'poster_path': '/26oSPnq0ct59l07QOXZKyzsiRtN.jpg', 'release_date': '2025-07-24', 'softcore': False, 'video': False, 'vote_average': 7.654, 'vote_count': 784}, {'adult': False, 'backdrop_path': '/hwwFyowfcbLRVmRBOkvnABBNIOs.jpg', 'genre_ids': [12, 16, 35, 10751], 'id': 9487, 'title': "A Bug's Life", 'original_language': 'en', 'original_title': "A Bug's Life", 'overview': 'On behalf of "oppressed bugs everywhere," an inventive ant named Flik hires a troupe of warrior bugs to defend his bustling colony from a horde of freeloading grasshoppers led by the evil-minded Hopper.', 'popularity': 13.6601, 'poster_path': '/Ah3J9OJVc2CNCuH2zMydXy9fmIC.jpg', 'release_date': '1998-11-25', 'softcore': False, 'video': False, 'vote_average': 6.979, 'vote_count': 9730}, {'adult': False, 'backdrop_path': '/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg', 'genre_ids': [12, 14, 16], 'id': 128, 'title': 'Princess Mononoke', 'original_language': 'ja', 'original_title': 'もののけ姫', 'overview': 'Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.', 'popularity': 13.5279, 'poster_path': '/cMYCDADoLKLbB83g4WnJegaZimC.jpg', 'release_date': '1997-07-12', 'softcore': False, 'video': False, 'vote_average': 8.321, 'vote_count': 8981}, {'adult': False, 'backdrop_path': '/k1pJslKr4aDayw9kWwWnlC3MIP3.jpg', 'genre_ids': [16, 14, 12], 'id': 615453, 'title': 'Ne Zha', 'original_language': 'zh', 'original_title': '哪吒之魔童降世', 'overview': 'A young boy is born as the reincarnation of a demonic power, into a society that hates and fears him. Destined by prophecy to bring destruction to the world, Nezha must choose between good and evil to see if he can change his fate.', 'popularity': 12.898, 'poster_path': '/phM9bb6s9c60LA8qwsdk7U1N2cS.jpg', 'release_date': '2019-07-26', 'softcore': False, 'video': False, 'vote_average': 7.908, 'vote_count': 866}, {'adult': False, 'backdrop_path': '/4Wftv3PCDTJM2NtTX3dfCF1DSNm.jpg', 'genre_ids': [28, 80, 53], 'id': 1421155, 'title': 'Ikatan Darah', 'original_language': 'id', 'original_title': 'Ikatan Darah', 'overview': 'A former martial arts athlete must face a network of loan sharks to save her younger brother, who is trapped in online gambling debt and risking their family’s safety.', 'popularity': 14.6189, 'poster_path': '/lF9amilOGIudUIq6NgDnz2YrPPa.jpg', 'release_date': '2026-04-30', 'softcore': False, 'video': False, 'vote_average': 6.5, 'vote_count': 4}, {'adult': False, 'backdrop_path': '/jniabJVBSW3EqLlyhjxWCZjVkiE.jpg', 'genre_ids': [12, 28, 878], 'id': 1895, 'title': 'Star Wars: Episode III - Revenge of the Sith', 'original_language': 'en', 'original_title': 'Star Wars: Episode III - Revenge of the Sith', 'overview': 'When the sinister Sith unveil a thousand-year-old plot to rule the galaxy, the Republic crumbles and from its ashes rises the evil Galactic Empire. Jedi hero Anakin Skywalker must choose a side.', 'popularity': 12.4737, 'poster_path': '/xfSAoBEm9MNBjmlNcDYLvLSMlnq.jpg', 'release_date': '2005-05-17', 'softcore': False, 'video': False, 'vote_average': 7.468, 'vote_count': 14948}, {'adult': False, 'backdrop_path': '/ihOJcrorpDQtHTzIOrobbOhpJsj.jpg', 'genre_ids': [12, 28, 53, 878], 'id': 604, 'title': 'The Matrix Reloaded', 'original_language': 'en', 'original_title': 'The Matrix Reloaded', 'overview': 'The Resistance builds in numbers as humans are freed from the Matrix and brought to the city of Zion. Neo discovers his superpowers, including the ability to see the code inside the Matrix. With machine sentinels digging to Zion in 72 hours, Neo, Morpheus and Trinity must find the Keymaker to ultimately reach the Source.', 'popularity': 11.4989, 'poster_path': '/aA5qHS0FbSXO8PxcxUIHbDrJyuh.jpg', 'release_date': '2003-05-15', 'softcore': False, 'video': False, 'vote_average': 7.076, 'vote_count': 11971}, {'adult': False, 'backdrop_path': '/85PMh0cKywekAJYDnRXfezYAmEc.jpg', 'genre_ids': [53, 28, 12, 878], 'id': 44833, 'title': 'Battleship', 'original_language': 'en', 'original_title': 'Battleship', 'overview': "When mankind beams a radio signal into space, a reply comes from ‘Planet G’, in the form of several alien crafts that splash down in the waters off Hawaii. Lieutenant Alex Hopper is a weapons officer assigned to the USS John Paul Jones, part of an international naval coalition which becomes the world's last hope for survival as they engage the hostile alien force of unimaginable strength. While taking on the invaders, Hopper must also try to live up to the potential that his brother, and his fiancée's father—an Admiral—expect of him.", 'popularity': 9.5082, 'poster_path': '/9b0Im7SfedHiajTwzSL9zGyBI7M.jpg', 'release_date': '2012-04-11', 'softcore': False, 'video': False, 'vote_average': 5.9, 'vote_count': 5964}, {'adult': False, 'backdrop_path': '/bacOuUnRBoAO1NjMfsAGX2EKRrS.jpg', 'genre_ids': [18], 'id': 1366, 'title': 'Rocky', 'original_language': 'en', 'original_title': 'Rocky', 'overview': "Rocky Balboa is a Philadelphia club fighter who seems to be going nowhere. But when a stroke of fate puts him in the ring with a world heavyweight champion, Rocky knows that it's his one shot at the big time — a once-in-a-lifetime opportunity to go the distance and come out a winner!", 'popularity': 10.782, 'poster_path': '/hEjK9A9BkNXejFW4tfacVAEHtkn.jpg', 'release_date': '1976-12-03', 'softcore': False, 'video': False, 'vote_average': 7.799, 'vote_count': 8623}, {'adult': False, 'backdrop_path': '/cT9ZfwoPDk8JbgkessmQgxAWiaM.jpg', 'genre_ids': [28, 878, 53], 'id': 1071585, 'title': 'M3GAN 2.0', 'original_language': 'en', 'original_title': 'M3GAN 2.0', 'overview': "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.", 'popularity': 9.9192, 'poster_path': '/oekamLQrwlJjRNmfaBE4llIvkir.jpg', 'release_date': '2025-06-25', 'softcore': False, 'video': False, 'vote_average': 7.207, 'vote_count': 1332}, {'adult': False, 'backdrop_path': '/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg', 'genre_ids': [16, 28, 14], 'id': 635302, 'title': 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train', 'original_language': 'ja', 'original_title': '劇場版「鬼滅の刃」無限列車編', 'overview': "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!", 'popularity': 10.2076, 'poster_path': '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg', 'release_date': '2020-10-16', 'softcore': False, 'video': False, 'vote_average': 8.21, 'vote_count': 4516}, {'adult': False, 'backdrop_path': '/kJYPag1YrA4PsXIftFdq3QEaanV.jpg', 'genre_ids': [12, 28, 53, 878], 'id': 605, 'title': 'The Matrix Revolutions', 'original_language': 'en', 'original_title': 'The Matrix Revolutions', 'overview': 'The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.', 'popularity': 9.4976, 'poster_path': '/bkkS61w94ZVMNVd8KEyyJl2tnY5.jpg', 'release_date': '2003-11-05', 'softcore': False, 'video': False, 'vote_average': 6.753, 'vote_count': 10817}, {'adult': False, 'backdrop_path': '/oGMomeS7bE43eN8SGJUaKvQnmud.jpg', 'genre_ids': [18], 'id': 70, 'title': 'Million Dollar Baby', 'original_language': 'en', 'original_title': 'Million Dollar Baby', 'overview': "Despondent over a painful estrangement from his daughter, trainer Frankie Dunn isn't prepared for boxer Maggie Fitzgerald to enter his life. But Maggie's determined to go pro and to convince Dunn and his cohort to help her.", 'popularity': 9.3606, 'poster_path': '/jcfEqKdWF1zeyvECPqp3mkWLct2.jpg', 'release_date': '2004-12-05', 'softcore': False, 'video': False, 'vote_average': 7.954, 'vote_count': 10366}, {'adult': False, 'backdrop_path': '/iYdgEUE2W2aJkgqfSjf1x3gFfuV.jpg', 'genre_ids': [28, 12, 878], 'id': 363088, 'title': 'Ant-Man and the Wasp', 'original_language': 'en', 'original_title': 'Ant-Man and the Wasp', 'overview': 'Just when his time under house arrest is about to end, Scott Lang once again puts his freedom at risk to help Hope van Dyne and Dr. Hank Pym dive into the quantum realm and try to accomplish, against time and any chance of success, a very dangerous rescue mission.', 'popularity': 7.2534, 'poster_path': '/cFQEO687n1K6umXbInzocxcnAQz.jpg', 'release_date': '2018-07-04', 'softcore': False, 'video': False, 'vote_average': 6.903, 'vote_count': 14194}, {'adult': False, 'backdrop_path': '/fTZlSRATSk7QJyUrpbmjScDtY8Z.jpg', 'genre_ids': [28, 53, 80, 18], 'id': 38234, 'title': 'Undisputed III: Redemption', 'original_language': 'en', 'original_title': 'Undisputed III: Redemption', 'overview': 'Russian inmate Boyka, now severely hobbled by the knee injury suffered at the end of Undisputed 2. No longer the feared prison fighter he was, he has declined so far that he is now good only for cleaning toilets. But when a new prison fight tournament begins - an international affair, matching the best fighters from prisons around the globe, enticing them with the promise of freedom for the winner - Boyka must reclaim his dignity and fight for his position in the tournament.', 'popularity': 8.1317, 'poster_path': '/g8KB77SPA7SyU8eid6TAEpt9skU.jpg', 'release_date': '2010-04-17', 'softcore': False, 'video': False, 'vote_average': 7.56, 'vote_count': 1022}], 'total_pages': 30, 'total_results': 592}

In [20]:
import requests

bearer_token = "bearer token/api read access token from tmdb"  ###api read access token from tmdb
url = "https://api.themoviedb.org/3/keyword/1721/movies"

headers = {
    "Authorization": f"Bearer {bearer_token}",
    "accept": "application/json"
}

response = requests.get(url, headers=headers)

if response.ok:
    data = response.json()
    print(data)
else:
    print(response.status_code, response.text)

{'id': 1721, 'page': 1, 'results': [{'adult': False, 'backdrop_path': '/pjlxrd646cBYznHoPBWTzz6FujX.jpg', 'genre_ids': [28, 878, 18], 'id': 39254, 'title': 'Real Steel', 'original_language': 'en', 'original_title': 'Real Steel', 'overview': 'Charlie Kenton is a washed-up fighter who retired from the ring when robots took over the sport. After his robot is trashed, he reluctantly teams up with his estranged son to rebuild and train an unlikely contender.', 'popularity': 78.628, 'poster_path': '/4GIeI5K5YdDUkR3mNQBoScpSFEf.jpg', 'release_date': '2011-09-28', 'softcore': False, 'video': False, 'vote_average': 7.097, 'vote_count': 9171}, {'adult': False, 'backdrop_path': '/zxi6WQPVc0uQAG5TtLsKvxYHApC.jpg', 'genre_ids': [16, 28, 14, 12], 'id': 980477, 'title': 'Ne Zha 2', 'original_language': 'zh', 'original_title': '哪吒之魔童闹海', 'overview': 'After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.', 'popularity': 44.5479, 'poster_path': '/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg', 'release_date': '2025-01-29', 'softcore': False, 'video': False, 'vote_average': 8.167, 'vote_count': 700}, {'adult': False, 'backdrop_path': '/xRyINp9KfMLVjRiO5nCsoRDdvvF.jpg', 'genre_ids': [18, 53], 'id': 550, 'title': 'Fight Club', 'original_language': 'en', 'original_title': 'Fight Club', 'overview': 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.', 'popularity': 27.9251, 'poster_path': '/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg', 'release_date': '1999-10-15', 'softcore': False, 'video': False, 'vote_average': 8.4, 'vote_count': 32086}, {'adult': False, 'backdrop_path': '/d354XqicJ7vi48YnPDr1vRk5uhZ.jpg', 'genre_ids': [28, 80, 18, 53], 'id': 49026, 'title': 'The Dark Knight Rises', 'original_language': 'en', 'original_title': 'The Dark Knight Rises', 'overview': "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.", 'popularity': 17.8328, 'poster_path': '/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg', 'release_date': '2012-07-17', 'softcore': False, 'video': False, 'vote_average': 7.796, 'vote_count': 24377}, {'adult': False, 'backdrop_path': '/zdXnJqBaGFVtLoPNuMeKfEYUViZ.jpg', 'genre_ids': [10749, 18], 'id': 11036, 'title': 'The Notebook', 'original_language': 'en', 'original_title': 'The Notebook', 'overview': "An epic love story centered around an older man who reads aloud to a woman with Alzheimer's. From a faded notebook, the old man's words bring to life the story about a couple who is separated by World War II, and is then passionately reunited, seven years later, after they have taken different paths.", 'popularity': 16.3556, 'poster_path': '/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg', 'release_date': '2004-06-25', 'softcore': False, 'video': False, 'vote_average': 7.888, 'vote_count': 12550}, {'adult': False, 'backdrop_path': '/8FWLJHuWB72UXBmiMtxwTvQVumN.jpg', 'genre_ids': [10751, 35, 80, 12, 16], 'id': 1175942, 'title': 'The Bad Guys 2', 'original_language': 'en', 'original_title': 'The Bad Guys 2', 'overview': 'The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.', 'popularity': 14.9456, 'poster_path': '/26oSPnq0ct59l07QOXZKyzsiRtN.jpg', 'release_date': '2025-07-24', 'softcore': False, 'video': False, 'vote_average': 7.654, 'vote_count': 784}, {'adult': False, 'backdrop_path': '/hwwFyowfcbLRVmRBOkvnABBNIOs.jpg', 'genre_ids': [12, 16, 35, 10751], 'id': 9487, 'title': "A Bug's Life", 'original_language': 'en', 'original_title': "A Bug's Life", 'overview': 'On behalf of "oppressed bugs everywhere," an inventive ant named Flik hires a troupe of warrior bugs to defend his bustling colony from a horde of freeloading grasshoppers led by the evil-minded Hopper.', 'popularity': 13.6601, 'poster_path': '/Ah3J9OJVc2CNCuH2zMydXy9fmIC.jpg', 'release_date': '1998-11-25', 'softcore': False, 'video': False, 'vote_average': 6.979, 'vote_count': 9730}, {'adult': False, 'backdrop_path': '/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg', 'genre_ids': [12, 14, 16], 'id': 128, 'title': 'Princess Mononoke', 'original_language': 'ja', 'original_title': 'もののけ姫', 'overview': 'Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.', 'popularity': 13.5279, 'poster_path': '/cMYCDADoLKLbB83g4WnJegaZimC.jpg', 'release_date': '1997-07-12', 'softcore': False, 'video': False, 'vote_average': 8.321, 'vote_count': 8981}, {'adult': False, 'backdrop_path': '/k1pJslKr4aDayw9kWwWnlC3MIP3.jpg', 'genre_ids': [16, 14, 12], 'id': 615453, 'title': 'Ne Zha', 'original_language': 'zh', 'original_title': '哪吒之魔童降世', 'overview': 'A young boy is born as the reincarnation of a demonic power, into a society that hates and fears him. Destined by prophecy to bring destruction to the world, Nezha must choose between good and evil to see if he can change his fate.', 'popularity': 12.898, 'poster_path': '/phM9bb6s9c60LA8qwsdk7U1N2cS.jpg', 'release_date': '2019-07-26', 'softcore': False, 'video': False, 'vote_average': 7.908, 'vote_count': 866}, {'adult': False, 'backdrop_path': '/4Wftv3PCDTJM2NtTX3dfCF1DSNm.jpg', 'genre_ids': [28, 80, 53], 'id': 1421155, 'title': 'Ikatan Darah', 'original_language': 'id', 'original_title': 'Ikatan Darah', 'overview': 'A former martial arts athlete must face a network of loan sharks to save her younger brother, who is trapped in online gambling debt and risking their family’s safety.', 'popularity': 14.6189, 'poster_path': '/lF9amilOGIudUIq6NgDnz2YrPPa.jpg', 'release_date': '2026-04-30', 'softcore': False, 'video': False, 'vote_average': 6.5, 'vote_count': 4}, {'adult': False, 'backdrop_path': '/jniabJVBSW3EqLlyhjxWCZjVkiE.jpg', 'genre_ids': [12, 28, 878], 'id': 1895, 'title': 'Star Wars: Episode III - Revenge of the Sith', 'original_language': 'en', 'original_title': 'Star Wars: Episode III - Revenge of the Sith', 'overview': 'When the sinister Sith unveil a thousand-year-old plot to rule the galaxy, the Republic crumbles and from its ashes rises the evil Galactic Empire. Jedi hero Anakin Skywalker must choose a side.', 'popularity': 12.4737, 'poster_path': '/xfSAoBEm9MNBjmlNcDYLvLSMlnq.jpg', 'release_date': '2005-05-17', 'softcore': False, 'video': False, 'vote_average': 7.468, 'vote_count': 14948}, {'adult': False, 'backdrop_path': '/ihOJcrorpDQtHTzIOrobbOhpJsj.jpg', 'genre_ids': [12, 28, 53, 878], 'id': 604, 'title': 'The Matrix Reloaded', 'original_language': 'en', 'original_title': 'The Matrix Reloaded', 'overview': 'The Resistance builds in numbers as humans are freed from the Matrix and brought to the city of Zion. Neo discovers his superpowers, including the ability to see the code inside the Matrix. With machine sentinels digging to Zion in 72 hours, Neo, Morpheus and Trinity must find the Keymaker to ultimately reach the Source.', 'popularity': 11.4989, 'poster_path': '/aA5qHS0FbSXO8PxcxUIHbDrJyuh.jpg', 'release_date': '2003-05-15', 'softcore': False, 'video': False, 'vote_average': 7.076, 'vote_count': 11971}, {'adult': False, 'backdrop_path': '/85PMh0cKywekAJYDnRXfezYAmEc.jpg', 'genre_ids': [53, 28, 12, 878], 'id': 44833, 'title': 'Battleship', 'original_language': 'en', 'original_title': 'Battleship', 'overview': "When mankind beams a radio signal into space, a reply comes from ‘Planet G’, in the form of several alien crafts that splash down in the waters off Hawaii. Lieutenant Alex Hopper is a weapons officer assigned to the USS John Paul Jones, part of an international naval coalition which becomes the world's last hope for survival as they engage the hostile alien force of unimaginable strength. While taking on the invaders, Hopper must also try to live up to the potential that his brother, and his fiancée's father—an Admiral—expect of him.", 'popularity': 9.5082, 'poster_path': '/9b0Im7SfedHiajTwzSL9zGyBI7M.jpg', 'release_date': '2012-04-11', 'softcore': False, 'video': False, 'vote_average': 5.9, 'vote_count': 5964}, {'adult': False, 'backdrop_path': '/bacOuUnRBoAO1NjMfsAGX2EKRrS.jpg', 'genre_ids': [18], 'id': 1366, 'title': 'Rocky', 'original_language': 'en', 'original_title': 'Rocky', 'overview': "Rocky Balboa is a Philadelphia club fighter who seems to be going nowhere. But when a stroke of fate puts him in the ring with a world heavyweight champion, Rocky knows that it's his one shot at the big time — a once-in-a-lifetime opportunity to go the distance and come out a winner!", 'popularity': 10.782, 'poster_path': '/hEjK9A9BkNXejFW4tfacVAEHtkn.jpg', 'release_date': '1976-12-03', 'softcore': False, 'video': False, 'vote_average': 7.799, 'vote_count': 8623}, {'adult': False, 'backdrop_path': '/cT9ZfwoPDk8JbgkessmQgxAWiaM.jpg', 'genre_ids': [28, 878, 53], 'id': 1071585, 'title': 'M3GAN 2.0', 'original_language': 'en', 'original_title': 'M3GAN 2.0', 'overview': "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.", 'popularity': 9.9192, 'poster_path': '/oekamLQrwlJjRNmfaBE4llIvkir.jpg', 'release_date': '2025-06-25', 'softcore': False, 'video': False, 'vote_average': 7.207, 'vote_count': 1332}, {'adult': False, 'backdrop_path': '/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg', 'genre_ids': [16, 28, 14], 'id': 635302, 'title': 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train', 'original_language': 'ja', 'original_title': '劇場版「鬼滅の刃」無限列車編', 'overview': "Tanjiro Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyojuro Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!", 'popularity': 10.2076, 'poster_path': '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg', 'release_date': '2020-10-16', 'softcore': False, 'video': False, 'vote_average': 8.21, 'vote_count': 4516}, {'adult': False, 'backdrop_path': '/kJYPag1YrA4PsXIftFdq3QEaanV.jpg', 'genre_ids': [12, 28, 53, 878], 'id': 605, 'title': 'The Matrix Revolutions', 'original_language': 'en', 'original_title': 'The Matrix Revolutions', 'overview': 'The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.', 'popularity': 9.4976, 'poster_path': '/bkkS61w94ZVMNVd8KEyyJl2tnY5.jpg', 'release_date': '2003-11-05', 'softcore': False, 'video': False, 'vote_average': 6.753, 'vote_count': 10817}, {'adult': False, 'backdrop_path': '/oGMomeS7bE43eN8SGJUaKvQnmud.jpg', 'genre_ids': [18], 'id': 70, 'title': 'Million Dollar Baby', 'original_language': 'en', 'original_title': 'Million Dollar Baby', 'overview': "Despondent over a painful estrangement from his daughter, trainer Frankie Dunn isn't prepared for boxer Maggie Fitzgerald to enter his life. But Maggie's determined to go pro and to convince Dunn and his cohort to help her.", 'popularity': 9.3606, 'poster_path': '/jcfEqKdWF1zeyvECPqp3mkWLct2.jpg', 'release_date': '2004-12-05', 'softcore': False, 'video': False, 'vote_average': 7.954, 'vote_count': 10366}, {'adult': False, 'backdrop_path': '/iYdgEUE2W2aJkgqfSjf1x3gFfuV.jpg', 'genre_ids': [28, 12, 878], 'id': 363088, 'title': 'Ant-Man and the Wasp', 'original_language': 'en', 'original_title': 'Ant-Man and the Wasp', 'overview': 'Just when his time under house arrest is about to end, Scott Lang once again puts his freedom at risk to help Hope van Dyne and Dr. Hank Pym dive into the quantum realm and try to accomplish, against time and any chance of success, a very dangerous rescue mission.', 'popularity': 7.2534, 'poster_path': '/cFQEO687n1K6umXbInzocxcnAQz.jpg', 'release_date': '2018-07-04', 'softcore': False, 'video': False, 'vote_average': 6.903, 'vote_count': 14194}, {'adult': False, 'backdrop_path': '/fTZlSRATSk7QJyUrpbmjScDtY8Z.jpg', 'genre_ids': [28, 53, 80, 18], 'id': 38234, 'title': 'Undisputed III: Redemption', 'original_language': 'en', 'original_title': 'Undisputed III: Redemption', 'overview': 'Russian inmate Boyka, now severely hobbled by the knee injury suffered at the end of Undisputed 2. No longer the feared prison fighter he was, he has declined so far that he is now good only for cleaning toilets. But when a new prison fight tournament begins - an international affair, matching the best fighters from prisons around the globe, enticing them with the promise of freedom for the winner - Boyka must reclaim his dignity and fight for his position in the tournament.', 'popularity': 8.1317, 'poster_path': '/g8KB77SPA7SyU8eid6TAEpt9skU.jpg', 'release_date': '2010-04-17', 'softcore': False, 'video': False, 'vote_average': 7.56, 'vote_count': 1022}], 'total_pages': 30, 'total_results': 592}

In [8]:
%whos   ###available vars

Variable       Type        Data/Info
------------------------------------
api_key        str         8b7e9938ad34ac933fc7b353b8bb44ea
bearer_token   str         eyJhbGciOiJIUzI1NiJ9.eyJh<...>JwWp8DxkYYTmwIVQR4YqA054k
data           dict        n=5
headers        dict        n=2
keyword_id     int         1721
movie          dict        n=15
params         dict        n=2
pd             module      <module 'pandas' from 'F:<...>es\\pandas\\__init__.py'>
requests       module      <module 'requests' from '<...>\\requests\\__init__.py'>
response       Response    <Response [200]>
url            str         https://api.themoviedb.org/3/keyword/1721/movies

In [9]:
print(locals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'requests', '_i2', 'api_key', 'keyword_id', 'url', 'params', 'response', 'data', '_i3', 'bearer_token', 'headers', '_i4', '_i5', 'movie', '_i6', '_i7', '_i8', '_i9'])

In [31]:
### fetching all page data from the tmdb website using api

import requests

TOKEN = "bearer token/api read access token from tmdb"  ###api read access token from tmdb
headers = {
    "Authorization": f"Bearer {TOKEN}",
    "accept": "application/json"
}

url = "https://api.themoviedb.org/3/keyword/1721/movies"

response = requests.get(url, headers=headers)
data = response.json()

print("Page no: ",data["page"])
print("Total Pages: ",data["total_pages"])
print("Total Results: ",data["total_results"])

Page no:  1
Total Pages:  30
Total Results:  592

In [32]:
###saving info of movies in movies variable

movies = []

for page in range(1, data["total_pages"] + 1):
    response = requests.get(
        url,
        headers=headers,
        params={"page": page}
    )

    page_data = response.json()
    movies.extend(page_data["results"])

print(f"Collected {len(movies)} movies")

Collected 592 movies

In [39]:
### all data extfrom

import pandas as pd

df = pd.DataFrame(movies)

df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/pjlxrd646cBYznHoPBWTzz6FujX.jpg,"[28, 878, 18]",39254,Real Steel,en,Real Steel,Charlie Kenton is a washed-up fighter who reti...,78.6280,/4GIeI5K5YdDUkR3mNQBoScpSFEf.jpg,2011-09-28,False,False,7.097,9171
1,False,/zxi6WQPVc0uQAG5TtLsKvxYHApC.jpg,"[16, 28, 14, 12]",980477,Ne Zha 2,zh,哪吒之魔童闹海,After a catastrophic event leaves their bodies...,44.5479,/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg,2025-01-29,False,False,8.167,700
2,False,/xRyINp9KfMLVjRiO5nCsoRDdvvF.jpg,"[18, 53]",550,Fight Club,en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,27.9251,/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg,1999-10-15,False,False,8.400,32086
3,False,/d354XqicJ7vi48YnPDr1vRk5uhZ.jpg,"[28, 80, 18, 53]",49026,The Dark Knight Rises,en,The Dark Knight Rises,Following the death of District Attorney Harve...,17.8328,/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg,2012-07-17,False,False,7.796,24377
4,False,/zdXnJqBaGFVtLoPNuMeKfEYUViZ.jpg,"[10749, 18]",11036,The Notebook,en,The Notebook,An epic love story centered around an older ma...,16.3556,/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg,2004-06-25,False,False,7.888,12550

In [41]:
table = df[
    [
        "id",
        "title",
        "release_date",
        "vote_average",
        "vote_count",
        "popularity"
    ]
]

table.head()

,id,title,release_date,vote_average,vote_count,popularity
0,39254,Real Steel,2011-09-28,7.097,9171,78.6280
1,980477,Ne Zha 2,2025-01-29,8.167,700,44.5479
2,550,Fight Club,1999-10-15,8.400,32086,27.9251
3,49026,The Dark Knight Rises,2012-07-17,7.796,24377,17.8328
4,11036,The Notebook,2004-06-25,7.888,12550,16.3556

In [42]:
table.to_csv("tmdb_movies.csv", index=False)

In [43]:
pd.read_csv("tmdb_movies.csv")

,id,title,release_date,vote_average,vote_count,popularity
0,39254,Real Steel,2011-09-28,7.097,9171,78.6280
1,980477,Ne Zha 2,2025-01-29,8.167,700,44.5479
2,550,Fight Club,1999-10-15,8.400,32086,27.9251
3,49026,The Dark Knight Rises,2012-07-17,7.796,24377,17.8328
4,11036,The Notebook,2004-06-25,7.888,12550,16.3556
...,...,...,...,...,...,...
587,1617197,Drink,2025-01-16,0.000,0,0.0311
588,531055,Garda of the Traditional Country,2015-10-31,9.000,1,0.0281
589,1705825,When Dogs Bite,2026-05-15,0.000,0,0.0168
590,1702438,The Great Fight,2025-06-21,0.000,0,0.0143
591,486989,Age of the Warrior,2017-11-11,1.000,1,0.0071